name: microsoft+vs2013-rtm-dskexp-enu
version: 12
maintainer:
  name: Mathieu Schroeter
  email: "schroeter@epsitec.ch"
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Microsoft Visual Studio Express 2013 for Windows Desktop.
  long: "Visual Studio Express 2013 for Windows Desktop enables the creation of desktop apps in C#, Visual Basic, and C++, and supports Windows Presentation Foundation (WPF), Windows Forms, and Win32."
dependency:
  toolchain+zog-peon:
    - ""
data:
  uri: "chest:vs2013_rtm_dskexp_enu.tar.gz"
  type: bin
  rules:
    type: exec
    bin: VS2013_RTM_DskExp_ENU/wdexpress_full.exe
    args:
      install: /Passive /NoRestart /NoWeb /Full
      remove: /Passive /NoRestart /NoWeb /Uninstall
  embedded: true
distribution: toolchain/
