subpackage:
  - runtime*
name: gnu+libncurses
version: 6.2-2
$version: '6.2'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: The ncurses library is a free software emulation of curses
  long: |-
    The ncurses (new curses) library is a free software emulation of curses in
    System V Release 4.0 (SVr4), and more. It uses terminfo format, supports
    pads and color and multiple highlights and forms characters and function-key
    mapping, and has all the other SVr4-curses enhancements over BSD curses.
    SVr4 curses became the basis of X/Open Curses.
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftpmirror.gnu.org/ncurses/ncurses-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION> ;
    ./configure --prefix=<PEON.PREFIXDIR>
                --enable-static
                --enable-shared
                --without-ada
                --disable-db-install
                --without-manpages
                --without-progs
                --without-tack
                --without-tests
                --enable-pc-files
                --without-shared
                --without-debug
                --without-profile
                --without-cxx-shared
                --without-termlib
                --without-ticlib
                --without-gpm
                --without-dlsym
                --without-pcre2
                --without-sysmouse
                --without-develop
  rules:
    type: make
    location: data/ncurses-<THIS.$VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
