subpackage:
  - runtime*
name: facebook+zstd
version: 1.5.4
$version: 1.5.4
distribution: monolith/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Zstandard - Fast real-time compression algorithm.
  long: |-
    Zstandard, or zstd as short version, is a fast lossless compression algorithm,
    targeting real-time compression scenarios at zlib-level and better compression
    ratios.
    It's backed by a very fast entropy stage, provided by Huff0 and FSE library.
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://github.com/facebook/zstd/releases/download/v<THIS.$VERSION>/zstd-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 0f470992aedad543126d06efab344dc5f3e171893810455787d38347343a4424.tar.gz
  type: src
  configure: ''
  rules:
    type: make
    location: data/zstd-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT> zstd-release HAVE_ZLIB=false HAVE_LZMA=false HAVE_LZ4=false'
      maketest: ''
      makeinstall: '-C programs install PREFIX=<PEON.PREFIXDIR>'
    test: none
    env:
      CFLAGS: <PEON.ENV.CFLAGS> -Os
  deploy: |-
    !{bash}
    <PEON.OS=win?
      strip -s {PEON.PREFIXDIR}/bin/*.exe; exit;
    :>
    <PEON.OS=darwin?
      strip -x {PEON.PREFIXDIR}/bin/zstd; exit;
    :>
    strip -s {PEON.PREFIXDIR}/bin/zstd
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
