subpackage:
  - 'runtime*'
name: gnu+m4
version: 1.4.17
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: M4
  long: ''
dependency:
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftp.gnu.org/gnu/m4/m4-<THIS.VERSION>.tar.gz'
    ref: ''
    out: ''
  type: src
  configure: '!cd <THIS.DATA.RULES.LOCATION> && ./configure --prefix=<PEON.PREFIXDIR>'
  rules:
    type: make
    location: 'data/m4-<THIS.VERSION>/'
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      makeinstall: install
  deploy: "rm ('<PEON.PREFIXDIR>/share/info/dir');"
  path: []
  embedded: true
  runtime:
    configure: ''
