subpackage:
  - runtime*
name: debian+dpkg
version: 1.19.7
$version: 1.19.7
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: DPKG
  long: ''
dependency:
  install:
    debian+fakeroot:
      - version: ''
        architecture: []
    wall+perl:
      - version: ''
        architecture: []
    debian+debhelper:
      - version: ''
        architecture: []
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    toolchain+build-essential:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_<THIS.$VERSION>.tar.xz'
    ref: ''
    out: ''
    externals: true
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> &&
    PERL_LIBDIR=<PEON.PREFIXDIR>/lib/perl5/site_perl ./configure --disable-nls
    --enable-static --disable-shared --disable-dselect
    --disable-start-stop-daemon --disable-update-alternatives
    --disable-devel-docs --prefix=<PEON.PREFIXDIR>
  rules:
    type: make
    location: data/dpkg-<THIS.$VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
  deploy: >-
    !touch <PEON.PREFIXDIR>/var/lib/dpkg/status && mkdir -p
    <PEON.PREFIXDIR>/etc/dpkg/origins && echo "Vendor: Debian\nVendor-URL:
    http://www.debian.org/\nBugs: debbugs://bugs.debian.org" >
    <PEON.PREFIXDIR>/etc/dpkg/origins/Debian
  env:
    path: []
    other:
      DPKG_DATADIR: <OS.ROOTDIR>/usr/share/dpkg
      DPKG_ADMINDIR: <OS.ROOTDIR>/usr/var/lib/dpkg
      DEB_VENDOR: Debian
  embedded: true
  runtime:
    configure: ''
