subpackage:
  - runtime*
name: gnu+wget
version: 1.21.4
$version: 1.21.4
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Wget.
  long: ''
dependency:
  install:
    openssl+openssl:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'http://ftpmirror.gnu.org/wget/wget-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 81542f5cefb8faacc39bbbc6c82ded80e3e4a88505ae72ea51df27525bcde04c.tar.gz
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --disable-nls
                     --without-libpsl
                     --with-ssl=openssl
    <PEON.OS=win?
                     --build=x86_64-w64-mingw32
                     --host=x86_64-w64-mingw32
                     --target=x86_64-w64-mingw32
                     LIBS="-lole32 -lbcrypt"
    :>
  rules:
    type: make
    location: data/wget-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: '<PEON.OS=win? install-exec : install >'
    test: none
    env:
      OPENSSL_CFLAGS: '-I<PEON.PROD.ROOTDIR>/usr/include'
      OPENSSL_LIBS: '-L<PEON.PROD.ROOTDIR>/usr/lib -lssl -lcrypto'
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
