subpackage:
  - runtime*
name: gnu+mpfr
version: 4.1.0-1
$version: 4.1.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: The GNU MPFR Library.
  long: |-
    The MPFR library is a C library for multiple-precision floating-point
    computations with correct rounding.
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture: []
    gnu+gmp:
      - version: '>= 5'
        architecture: []
data:
  get:
    uri: 'https://ftp.gnu.org/gnu/mpfr/mpfr-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 3127fe813218f3a1f0adf4e8899de23df33b4cf4b4b3831a5314f78e65ffa2d6.tar.gz
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION> ;
    ./configure --prefix=<PEON.PREFIXDIR>
                --disable-shared
                --enable-static
  rules:
    type: make
    location: data/mpfr-<THIS.$VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
  deploy: rm('<PEON.PREFIXDIR>/share/info/dir');
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
