name: toolchain+msysgit
version: 1.9.5-preview20141217
maintainer:
  name: Mathieu Schroeter
  email: "schroeter@epsitec.ch"
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Git is a free and open source distributed version control system.
  long: Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.
dependency:
  toolchain+xcraft-peon:
    - ""
  toolchain+7z:
    - ""
data:
  uri: "https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20141217/PortableGit-1.9.5-preview20141217.7z"
  type: bin
  configure: ""
  rules:
    type: copy
    location: ""
    args:
      postinst: ""
      prerm: ""
  embedded: true
distribution: toolchain/
