name: debian+lintian
version: 2.16.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - linux-i386
  - linux-amd64
description:
  brief: Dissects Debian packages and reports bugs and policy violations.
  long: ''
dependency:
  install:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    wall+perl:
      - version: ''
        architecture: []
    perl+io-async:
      - version: ''
        architecture: []
    perl+future:
      - version: ''
        architecture: []
    perl+struct-dumb:
      - version: ''
        architecture: []
    perl+list-moreutils:
      - version: ''
        architecture: []
    perl+exporter-tiny:
      - version: ''
        architecture: []
    perl+ipc-run:
      - version: ''
        architecture: []
    perl+clone:
      - version: ''
        architecture: []
    perl+file-basedir:
      - version: ''
        architecture: []
    perl+class-accessor:
      - version: ''
        architecture: []
    perl+path-tiny:
      - version: ''
        architecture: []
    perl+cgi:
      - version: ''
        architecture: []
    debian+dpkg:
      - version: ''
        architecture: []
    perl+list-compare:
      - version: ''
        architecture: []
    perl+moo:
      - version: ''
        architecture: []
    perl+parse-debianchangelog:
      - version: ''
        architecture: []
    perl+archive-zip:
      - version: ''
        architecture: []
    perl+xml-simple:
      - version: ''
        architecture: []
    debian+aptpkg:
      - version: ''
        architecture: []
data:
  get:
    uri: >-
      https://salsa.debian.org/lintian/lintian/-/archive/<THIS.VERSION>/lintian-<THIS.VERSION>.tar.gz
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: >-
    mv('data/lintian-<THIS.VERSION>', 'root/usr/share/lintian');
    mkdir('root/usr/bin'); sed('root/usr/share/lintian/frontend/dplint',
    /^#!\/usr\/bin\/perl -w/, '#!/usr/bin/env -S perl -w');
    ln('../share/lintian/frontend/lintian', 'root/usr/bin/lintian');
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
    other: {}
  embedded: true
