subpackage:
  - runtime*
name: x-aarch64-linux+gnu-gcc-glibc-cross
version: 10.2-2.32-15
$version: 10.2-2.32
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: AARCH64 GCC/glibc cross-compiler
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    xcraft+utils:
      - version: ''
        architecture: []
    estes+flex:
      - version: ''
        architecture: []
    gnu+m4:
      - version: ''
        architecture: []
    gnu+bison:
      - version: ''
        architecture: []
    gnu+wget:
      - version: ''
        architecture: []
    samba+ccache-gcc:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
    samba+ccache-clang:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
    wall+perl:
      - version: ''
        architecture: []
    gnu+coreutils:
      - version: ''
        architecture: []
    gnu+gmp:
      - version: '>= 4.3.2'
        architecture: []
    gnu+mpfr:
      - version: '>= 2.4.2'
        architecture: []
    gnu+mpc:
      - version: '>= 0.8.1'
        architecture: []
    inria+isl:
      - version: '>= 0.15'
        architecture: []
    gnu+gawk:
      - version: ''
        architecture: []
    vanrossum+python3:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-binutils:
      - version: ''
        architecture: []
    x-aarch64-linux+linux-kernel:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-glibc:
      - version: ''
        architecture: []
    samba+rsync:
      - version: ''
        architecture: []
data:
  get:
    uri: ''
    ref: ''
    out: ''
    externals: false
    prepare: ''
  type: src
  configure: |-
    mkdir('data/binutils');
    mkdir('data/gcc');
    mkdir('data/glibc');
  rules:
    type: script
    location: data
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !export PATH="<PEON.PREFIXDIR>/bin:$PATH"
                CFLAGS= CXXFLAGS= LDFLAGS= CPPFLAGS=
        && _CC=$CC _CXX=$CXX

        && : /// binutils ///
          && cd binutils
          && CONFIGURE="<PEON.ROOTDIR>/var/x-aarch64-linux/binutils/configure"
          && $CONFIGURE --prefix="<PEON.PREFIXDIR>"
                        --target=aarch64-linux
                        --disable-multilib
                        --disable-nls
                        --with-gmp=<PEON.ROOTDIR>/usr
                        --with-mpfr=<PEON.ROOTDIR>/usr
                        --with-mpc=<PEON.ROOTDIR>/usr
                        --with-isl=<PEON.ROOTDIR>/usr
          && make -j<PEON.CPUS.COUNT>
          && make install
          && cd ..

        && : /// gcc - stage 0 ///
          && cd gcc
          && CONFIGURE="<PEON.ROOTDIR>/var/x-aarch64-linux/gcc/configure"
          && $CONFIGURE --prefix="<PEON.PREFIXDIR>"
                        --enable-languages=c,c++
                        --target=aarch64-linux
                        --enable-static
                        --enable-shared
                        --enable-host-shared
                        --disable-multilib
                        --disable-nls
                        --disable-libssp
                        --with-pic
                        --with-gmp=<PEON.ROOTDIR>/usr
                        --with-mpfr=<PEON.ROOTDIR>/usr
                        --with-mpc=<PEON.ROOTDIR>/usr
                        --with-isl=<PEON.ROOTDIR>/usr
          && make -j<PEON.CPUS.COUNT> all-gcc
          && make install-gcc
          && cd ..

        && : /// linux - headers ///
          && make -C "<PEON.ROOTDIR>/var/x-aarch64-linux/linux"
                  ARCH=arm64
                  INSTALL_HDR_PATH="<PEON.PREFIXDIR>/aarch64-linux"
                  headers_install

        && : /// glibc - stage 0 ///
          && cd glibc
          && unset CC CXX
          && CONFIGURE="<PEON.ROOTDIR>/var/x-aarch64-linux/glibc/configure"
          && $CONFIGURE --prefix="<PEON.PREFIXDIR>/aarch64-linux"
                        --build=$MACHTYPE
                        --host=aarch64-linux
                        --target=aarch64-linux
                        --with-headers="<PEON.PREFIXDIR>/aarch64-linux/include"
                        --disable-multilib
                        libc_cv_forced_unwind=yes
          && make install-bootstrap-headers=yes install-headers
          && make -j<PEON.CPUS.COUNT> csu/subdir_lib'
          && install csu/crt1.o csu/crti.o csu/crtn.o -t "<PEON.PREFIXDIR>/aarch64-linux/lib" -D
          && aarch64-linux-gcc -nostdlib -nostartfiles -shared -x c /dev/null
                               -o "<PEON.PREFIXDIR>/aarch64-linux/lib/libc.so"
          && touch "<PEON.PREFIXDIR>/aarch64-linux/include/gnu/stubs.h"
          && cd ..

        && : /// gcc - stage 1 ///
          && cd gcc
          && export CC=$_CC CXX=$_CXX
          && make -j<PEON.CPUS.COUNT> all-target-libgcc
          && make install-target-libgcc
          && cd ..

        && : /// glibc - stage 1 ///
          && cd glibc
          && unset CC CXX
          && make -j<PEON.CPUS.COUNT>
          && make install
          && cd ..

        && : /// gcc - stage 2 ///
          && cd gcc
          && export CC=$_CC CXX=$_CXX
          && make -j<PEON.CPUS.COUNT> all-target-libstdc++-v3
          && make install-target-libstdc++-v3
      maketest: ''
      makeinstall: ''
    test: none
  deploy: |-
    rm('<PEON.PREFIXDIR>/share/info');
    rm('<PEON.PREFIXDIR>/share/man/man7');
    rm('<PEON.PREFIXDIR>/share/gcc-10.2.0');
    mkdir('<PEON.PREFIXDIR>/local/bin');
    const exp =
      'unset CPLUS_INCLUDE_PATH\n' +
      'LIBRARY_PATH=${XCRAFT_DEVROOT}/usr/aarch64-linux/lib\n' +
      'C_INCLUDE_PATH=${XCRAFT_DEVROOT}/usr/aarch64-linux/include\n' +
      'if [ ! -z "${PEON_SHARE}" ]; then\n' +
      '    CCACHE_BASEDIR=${PEON_SHARE}\n' +
      'else\n' +
      '    CCACHE_BASEDIR=${XCRAFT_TARGETROOT}\n' +
      'fi\n' +
      'export LIBRARY_PATH C_INCLUDE_PATH CCACHE_BASEDIR\n';
    for (const bin of ['gcc', 'g++', 'ld']) {
      const ccache = bin !== 'ld' ? 'CCACHE=\ncommand -v ccache >/dev/null 2>&1 && CCACHE=ccache\n$CCACHE ' : '';
      yield exec(
        'writefile',
        `#!/bin/bash\n\n${exp}\n${ccache}"$(dirname "$0")/../../bin/aarch64-linux-${bin}" "$@"\n`,
        `<PEON.PREFIXDIR>/local/bin/aarch64-linux-${bin}`
      );
      chmod(`<PEON.PREFIXDIR>/local/bin/aarch64-linux-${bin}`, 0o755);
    }
  env:
    path:
      - usr/local/bin
    other: {}
  embedded: true
  runtime:
    configure: ''
