name: microsoft+vs2013-rtm-dskexp-enu
version: 12
maintainer:
  name: Mathieu Schroeter
  email: "schroeter@epsitec.ch"
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Microsoft Visual Studio Express 2013 for Windows Desktop.
  long: "Visual Studio Express 2013 for Windows Desktop enables the creation of desktop apps in C#, Visual Basic, and C++, and supports Windows Presentation Foundation (WPF), Windows Forms, and Win32."
dependency:
  runtime:
    bootstrap+xcraft-peon:
      - ""
data:
  get:
    uri: "chest:vs2013_rtm_dskexp_enu.tar.gz"
    out: ""
  type: bin
  configure: ""
  rules:
    type: exec
    location: data/VS2013_RTM_DskExp_ENU/wdexpress_full.exe
    args:
      postinst: /Passive /NoRestart /NoWeb /Full
      prerm: /Passive /NoRestart /NoWeb /Uninstall
  path: []
  embedded: true
distribution: toolchain/
