subpackage:
  - runtime*
name: xamarin+mono
version: 4.6.2.7
$version: 4.6.2.7
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Mono is an open source implementation of Microsoft's .NET Framework.
  long: ''
dependency:
  install:
    gnu+libiconv:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    gnu+automake:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://download.mono-project.com/sources/mono/mono-<THIS.$VERSION>.tar.bz2'
    ref: ''
    out: ''
    externals: true
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && CFLAGS="$CFLAGS -std=gnu99"
    CXXFLAGS="$CXXFLAGS -std=c++11" C_INCLUDE_PATH="<PEON.ROOTDIR>/usr/include"
    ./configure --prefix=<PEON.PREFIXDIR> --disable-nls --disable-libraries
    --enable-small-config --disable-boehm --with-xen_opt=no --without-x
    --with-monodroid=no --with-monotouch=no --with-xammac=no --with-mcs-docs=no
    --disable-system-aot <PEON.OS=darwin?--with-tls=pthread:>
  rules:
    type: make
    location: data/mono-4.6.2/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: '!mozroots --import --sync'
