data:
  configure: |-
    !<PEON.OS=win? exit 0; :>
    cd <THIS.DATA.RULES.LOCATION> &&
    <PEON.OS=darwin?
      SDKROOT="$MACOSSDK_1013"
      MACOSX_DEPLOYMENT_TARGET=10.10
    :> ./configure --prefix=<PEON.PREFIXDIR>
                   --libdir=<PEON.PREFIXDIR.DEV>/lib
                   --includedir=<PEON.PREFIXDIR.DEV>/include
                   --static
  rules:
    args:
      makeall: |-
        !<PEON.OS=darwin?
          SDKROOT="$MACOSSDK_1013"
          MACOSX_DEPLOYMENT_TARGET=10.10
        :> make -j<PEON.CPUS.COUNT>
