subpackage:
  - runtime*
  - dev
name: adler+zlib
version: 1.2.12
$version: 1.2.12
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: A Massively Spiffy Yet Delicately Unobtrusive Compression Library
  long: ''
dependency:
  install:
    adler+zlib:
      - version: ''
        architecture: []
        subpackage:
          - dev
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
data:
  get:
    uri: 'https://zlib.net/zlib-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9.tar.gz
  type: src
  configure: |-
    !<PEON.OS=win? exit 0; :>
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --libdir=<PEON.PREFIXDIR.DEV>/lib
                     --includedir=<PEON.PREFIXDIR.DEV>/include
  rules:
    type: script
    location: data/zlib-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!make <PEON.OS=win? -f win32/Makefile.gcc : -j{PEON.CPUS.COUNT}>'
      maketest: ''
      makeinstall: |-
        !make BINARY_PATH=<PEON.PREFIXDIR>/bin
              INCLUDE_PATH=<PEON.PREFIXDIR.DEV>/include
              LIBRARY_PATH=<PEON.PREFIXDIR.DEV>/lib
        <PEON.OS=win?
              SHARED_MODE=1
              -f win32/Makefile.gcc
        :>    install
    test: none
    env: {}
  deploy: |-
    mkdir("<PEON.PREFIXDIR>/lib");
    try { /* lib/ is not defined with pure --shared build */
      mv("<PEON.PREFIXDIR.DEV>/lib", "<PEON.PREFIXDIR>/lib", /.*[.]so.*/);
    } catch (ex) {}
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
