name: microsoft+buildtools
version: "12"
maintainer:
  name: Mathieu Schroeter
  email: "schroeter@epsitec.ch"
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Microsoft Build Tools.
  long: Build Tools 2013 provides the essential tools for building managed applications.
dependency:
  runtime:
    bootstrap+xcraft-peon:
      - ""
data:
  get:
    uri: "http://download.microsoft.com/download/9/B/B/9BB1309E-1A8F-4A47-A6C5-ECF76672A3B3/BuildTools_Full.exe"
    out: ""
  type: bin
  configure: ""
  rules:
    type: exec
    location: BuildTools_Full.exe
    args:
      postinst: /Q /S /Passive /NoRestart /NoWeb /Full
      prerm: /Q /S /Passive /NoRestart /NoWeb /Uninstall
  path: []
  embedded: true
distribution: toolchain/
