subpackage:
  - runtime*
name: openjs+nodejs8
version: 8.17.0-42
$version: 8.17.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Node.js is a JS runtime built on Chrome's V8 JavaScript engine.
  long: ''
dependency:
  install:
    openssl+openssl:
      - version: ''
        architecture: []
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    vanrossum+python2:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://nodejs.org/dist/latest-v8.x/node-v<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: aa583f19065545fa4c9b480ba13cf94f29350415ca5a853a5afde3c9b6982c4b.tar.gz
  type: src
  configure: |-
    !{bash}
    <PEON.OS=win?
      cp -rf "{THIS.DATA.RULES.LOCATION}" "{PEON.ROOTTEMP}"
        && cd "{PEON.ROOTTEMP}/node-v{THIS.$VERSION}"
    :
      cd <THIS.DATA.RULES.LOCATION>
    >
        && ./configure --prefix=<PEON.INSTALLDIR>/opt/node8
                       --enable-static
                       --partly-static
                       --without-dtrace
                       --without-intl
                       --without-snapshot
                       --without-perfctr
                       --without-etw
                       --shared-openssl
                       --shared-openssl-includes={PEON.ROOTDIR}/usr/include
                       --shared-openssl-libpath={PEON.ROOTDIR}/usr/lib
    <PEON.OS=win?
                       --dest-os=win
    :>
  rules:
    type: script
    location: data/node-v<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !{bash}
        <PEON.OS=win?
          cd "{PEON.ROOTTEMP}/node-v{THIS.$VERSION}"
            && python2 tools/gyp_node.py -f make
            && touch config.gypi
            && make out/Release/obj/gen/src/inspector/protocol/Forward.h
            && sed -i 's#-Wl,--whole-archive,$(builddir)/obj#-Wl,--whole-archive,$(builddir)/obj.target#g' node.target.mk
            && sed -i 's#-Wl,--whole-archive,$(builddir)/obj#-Wl,--whole-archive,$(builddir)/obj.target#g' cctest.target.mk
            && make -j{PEON.CPUS.COUNT}
        :
          make -j{PEON.CPUS.COUNT}
        >
      maketest: ''
      makeinstall: |-
        !{bash}
        <PEON.OS=win?
          cd "{PEON.ROOTTEMP}/node-v{THIS.$VERSION}"
            && python2 tools/install.py install "{PEON.INSTALLDIR}/opt/node8" "./"
            && install -m755 "deps/npm/bin/npm.cmd" "{PEON.INSTALLDIR}/opt/node8/bin/npm.cmd"
          ;
        :
          make install ;
        >
        <PEON.OS=win?
          rm -rf "{PEON.ROOTTEMP}/node-v{THIS.$VERSION}"
        :>
    test: none
    env:
      win/CXXFLAGS: <PEON.ENV.CXXFLAGS> -D_WIN32_WINNT=0x0600
      win/LDFLAGS: '-municode'
  deploy: ''
  env:
    path: []
    other:
      NODE8: <OS.ROOTDIR>/opt/node8/bin
  embedded: true
  runtime:
    configure: ''
