subpackage:
  - runtime*
name: google+go
version: 1.16.3
$version: 1.16.3
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: GO lang
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    google+go-bootstrap:
      - version: ''
        architecture: []
    apple+macos-sdk-1013:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
data:
  get:
    uri: 'https://dl.google.com/go/go<THIS.$VERSION>.src.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: ''
  rules:
    type: script
    location: data/go
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !<PEON.OS=darwin?
          export SDKROOT="$MACOSSDK_1013" &&
        :>
        cd src &&
        <PEON.OS=win? make.bat : ./make.bash >
      maketest: ''
      makeinstall: |-
        mkdir('<PEON.INSTALLDIR>/opt');
        cp('../go', '<PEON.INSTALLDIR>/opt/go');
    test: none
  deploy: ''
  env:
    path:
      - opt/go/bin
    other:
      GOROOT: <OS.ROOTDIR>/opt/go
  embedded: true
  runtime:
    configure: ''
