subpackage:
  - runtime*
name: google+go
version: 1.17.6-1
$version: 1.17.6
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: GO lang
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    google+go-bootstrap:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - mswindows-i386
          - mswindows-amd64
    google+go-bootstrap-darwin:
      - version: ''
        architecture:
          - darwin-amd64
          - darwin-aarch64
    apple+macos-sdk-1013:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
data:
  get:
    uri: 'https://dl.google.com/go/go<THIS.$VERSION>.src.tar.gz'
    mirrors: []
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 4dc1bbf3ff61f0c1ff2b19355e6d88151a70126268a47c761477686ef94748c8.tar.gz
  type: src
  configure: ''
  rules:
    type: script
    location: data/go
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !cd src &&
        <PEON.OS=win? make.bat : ./make.bash >
      maketest: ''
      makeinstall: |-
        mkdir('<PEON.INSTALLDIR>/opt');
        cp('../go', '<PEON.INSTALLDIR>/opt/go');
    test: none
    env:
      darwin/SDKROOT: <PEON.ENV.MACOSSDK_1013>
  deploy: ''
  env:
    path:
      - opt/go/bin
    other:
      GOROOT: <OS.ROOTDIR>/opt/go
  embedded: true
  runtime:
    configure: ''
