name: toolchain+zog-peon
version: 0.1.0
maintainer:
  name: Mathieu Schroeter
  email: "schroeter@epsitec.ch"
architecture:
  - all
description:
  brief: A core dependency for many packages.
  long: ""
dependency:
  toolchain+nodejs-targz:
    - ">= 0.1.1"
data:
  uri: "self:///root"
  type: bin
  rules:
    type: copy
    location: ""
    args:
      install: ""
      remove: ""
  embedded: true
distribution: toolchain/
