name: xcraft+base-build
version: 0.1.0
$version: 0.1.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - linux-i386
  - linux-amd64
  - linux-aarch64
  - darwin-i386
  - darwin-amd64
  - darwin-aarch64
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Base development packages.
  long: ''
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
    nixos+patchelf:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
    kitware+cmake:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    schindelin+mingit:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
    torvalds+git:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    kaspar030+git-cache:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    xcraft+build-essential:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    pavlov+7z:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
data:
  get:
    uri: ''
    ref: ''
    out: ''
    externals: false
  type: bin
  configure: ''
  rules:
    type: meta
    location: ''
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
    other: {}
  embedded: true
