name: microsoft+dotnet-sdk-linux
version: 3.1.406
$version: 3.1.406
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - linux-amd64
description:
  brief: .NET Core SDK
  long: ''
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
    bagder+curl:
      - version: ''
        architecture: []
  make:
    xcraft+utils:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://download.visualstudio.microsoft.com/download/pr/d7b8da76-a160-44a1-8038-b4b91404b8f2/af410f6d2e213ef7ee9dfefd853e97c0/dotnet-sdk-<THIS.$VERSION>-linux-x64.tar.gz'
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: |-
    mv('data', 'root/opt/dotnet-sdk');
    mkdir('root/opt/dotnet-sdk/bin');
    yield exec(
      'writefile',
      '#!/bin/bash\nexport LD_LIBRARY_PATH=${LIBRARY_PATH}\n"$(dirname "$0")/../dotnet" "$@"\n',
      'root/opt/dotnet-sdk/bin/dotnet'
    );
    yield exec('chmod', 'a+x', 'root/opt/dotnet-sdk/bin/dotnet');
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
  env:
    path:
      - opt/dotnet-sdk/bin
    other:
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
  embedded: true
