subpackage:
  - runtime*
name: raspberry+pi4b-linux-kernel
version: 20250127
$version: 20250127
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: The Linux Kernel for RASPBERRY Pi4 model B
  long: ''
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
  make:
    xcraft+base-make:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://github.com/raspberrypi/linux/archive/refs/tags/stable_<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && make ARCH=arm64 CROSS_COMPILE=aarch64-xcraft-linux-gnu- bcm2711_defconfig
  rules:
    type: script
    location: data/linux-stable_<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !make ARCH=arm64
              CROSS_COMPILE=aarch64-xcraft-linux-gnu-
              -j<PEON.CPUS.COUNT>
              Image modules dtbs
      maketest: ''
      makeinstall: |-
        !    mkdir -p "<PEON.INSTALLDIR>/var/carnotzet/boot"
          && mkdir -p "<PEON.INSTALLDIR>/var/carnotzet/rootfs"
          && make ARCH=arm64
                  CROSS_COMPILE=aarch64-xcraft-linux-gnu-
                  INSTALL_MOD_PATH="<PEON.INSTALLDIR>/var/carnotzet/rootfs"
                  modules_install
          && cp -a arch/arm64/boot/Image "<PEON.INSTALLDIR>/var/carnotzet/boot/"
          && cp -a arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb "<PEON.INSTALLDIR>/var/carnotzet/boot/"
    test: none
    env:
      KBUILD_BUILD_TIMESTAMP: ''
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
