subpackage:
  - runtime*
name: freedesktop+fontconfig
version: 2.14.2
$version: 2.14.2
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Fontconfig
  long: ''
dependency:
  install:
    clark+expat:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    gnu+libiconv:
      - version: ''
        architecture: []
    nongnu+freetype:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    adler+zlib-dev:
      - version: ''
        architecture: []
    seward+bzip2:
      - version: ''
        architecture: []
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    gnu+gperf:
      - version: ''
        architecture: []
  make:
    xcraft+base-make:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://www.freedesktop.org/software/fontconfig/release/fontconfig-<THIS.$VERSION>.tar.xz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: dba695b57bce15023d2ceedef82062c2b925e51f5d4cc4aef736cf13f60a468b.tar.xz
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --enable-iconv
                     --disable-docs
                     --disable-nls
  rules:
    type: make
    location: data/fontconfig-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other:
      FONTCONFIG_SYSROOT: <OS.PROD.ROOTDIR>/
      FONTCONFIG_PATH: <OS.PROD.ROOTDIR>/usr/etc/fonts/
  embedded: true
  runtime:
    configure: ''
