name: kaspar030+git-cache
version: 0.2.0-5
$version: 0.2.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - linux-i386
  - linux-amd64
  - linux-aarch64
  - darwin-i386
  - darwin-amd64
  - darwin-aarch64
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Simple git cache management script
  long: ''
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
    torvalds+git:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    schindelin+mingit:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
data:
  get:
    uri: 'https://github.com/kaspar030/git-cache/archive/36e2d0a1ed6e7a1becfd3d5f03efae84c7d3ec46.zip'
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: |-
    mv('data/git-cache-36e2d0a1ed6e7a1becfd3d5f03efae84c7d3ec46/git-cache',
       'root/usr/bin/git-cache'); chmod('root/usr/bin/git-cache', 0o755);
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
    other:
      GIT_CACHE_DIR: <OS.ROOTTEMP>/git-cache
      GIT_CACHE_VERBOSE: '1'
  embedded: true
