subpackage:
  - runtime*
name: x-aarch64-linux+gnu-glibc-stage0
version: 2.32-28
$version: '2.32'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: The GNU C Library
  long: ''
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+base-build:
      - version: ''
        architecture: []
    gnu+gawk:
      - version: ''
        architecture: []
    vanrossum+python3:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-stage0:
      - version: ''
        architecture: []
    x-aarch64-linux+linux-headers:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftpmirror.gnu.org/glibc/glibc-<THIS.$VERSION>.tar.xz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !rm -rf "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux+gnu-glibc"
      && cp -a data/glibc-<THIS.$VERSION> "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux+gnu-glibc"
      && cd "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux+gnu-glibc"
      && (mkdir objdir || :)
      && cd objdir
      && export PATH="<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/bin:$PATH"
                CC= CXX= CFLAGS= CXXFLAGS= LDFLAGS= CPPFLAGS=
      && ../configure --prefix="<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/aarch64-linux"
                      --build=$MACHTYPE
                      --host=aarch64-linux
                      --target=aarch64-linux
                      --with-headers=<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/aarch64-linux/include
                      --disable-multilib
                      libc_cv_forced_unwind=yes
  rules:
    type: script
    location: data/glibc-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !export PATH="<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/bin:$PATH"
                CC= CXX= CFLAGS= CXXFLAGS= LDFLAGS= CPPFLAGS=
          && cd "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux+gnu-glibc/objdir"
          && make install-bootstrap-headers=yes install-headers
          && make -j<PEON.CPUS.COUNT> csu/subdir_lib'
      maketest: ''
      makeinstall: |-
        !export PATH="<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/bin:$PATH"
                CC= CXX= CFLAGS= CXXFLAGS= LDFLAGS= CPPFLAGS=
          && cd "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux+gnu-glibc/objdir"
          && install csu/crt1.o csu/crti.o csu/crtn.o -t "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/aarch64-linux/lib" -D
          && aarch64-linux-gcc -nostdlib -nostartfiles -shared -x c /dev/null
                               -o "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/aarch64-linux/lib/libc.so"
          && touch "<PEON.ROOTDIR>/var/tmp/x-aarch64-linux/aarch64-linux/include/gnu/stubs.h"
          && touch ../xcraft-stage0
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
