name: toolchain+nodejs-targz
version: 0.1.1
maintainer:
  name: Mathieu Schroeter
  email: "schroeter@epsitec.ch"
architecture:
  - all
description:
  brief: Easily extract tar.gz archives with node.js.
  long: ""
dependency: {}
data:
  uri: ""
  type: bin
  rules:
    type: copy
    location: ""
    args:
      install: ""
      remove: ""
  embedded: true
distribution: toolchain/
