name: microsoft+buildtools-net452
version: 15.7.27703.2026
$version: 15.7.27703.2026
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Visual NET 4.5.2 build tools.
  long: Visual NET 4.5.2 build tools.
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'chest:microsoft+buildtools-net452.zip'
    ref: ''
    out: ''
    externals: true
    $hash: 94b20f7dc3c139227cb946c932f97d81615299b9a0c9ae2157d3fe911a0d1f05.zip
  type: bin
  configure: ''
  rules:
    type: exec
    location: data/microsoft+buildtools-net452/vs_BuildTools.exe
    args:
      postinst: >-
        --locale En-us --installPath
        <PEON.ROOTDRIVE>/xcraft/microsoft/buildtools --add
        Microsoft.Net.Component.4.5.2.TargetingPack --add
        Microsoft.VisualStudio.Component.NuGet.BuildTools --quiet --norestart
        --wait --nocache --noUpdateInstaller
      prerm: >-
        --locale En-us --installPath
        <PEON.ROOTDRIVE>/xcraft/microsoft/buildtools --remove
        Microsoft.Net.Component.4.5.2.TargetingPack --remove
        Microsoft.VisualStudio.Component.NuGet.BuildTools --quiet --norestart
        --wait --noUpdateInstaller
  env:
    path:
      - <OS.ROOTDRIVE>/xcraft/microsoft/buildtools/MSBuild/15.0/Bin
    other: {}
  embedded: true
