subpackage:
  - runtime*
name: boostorg+boost
version: 1.72.0
$version: 1.72.0
distribution: westeros/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Boost provides free peer-reviewed portable C++ source libraries.
  long: ''
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://download.sourceforge.net/boost/boost/<THIS.$VERSION>/boost_1_72_0.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./bootstrap.sh --prefix=<PEON.PREFIXDIR>
                        --without-icu
  rules:
    type: script
    location: data/boost_1_72_0
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !./b2 --prefix=<PEON.PREFIXDIR>
              --build-type=minimal
              --layout=system
                variant=release
                link=static
                runtime-link=static
              install'
      maketest: ''
      makeinstall: ''
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
