name: xcraft+build-essential
version: 0.0.1
$version: 0.0.1
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - linux-i386
  - linux-amd64
  - linux-aarch64
  - darwin-i386
  - darwin-amd64
  - darwin-aarch64
  - solaris-i386
  - solaris-amd64
  - freebsd-i386
  - freebsd-amd64
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Essential tools for building.
  long: ''
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+bash:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
    gnu+gcc:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
    msys2+mingw:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
    gnu+binutils:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
    gnu+make:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
    samba+ccache-gcc:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - mswindows-i386
          - mswindows-amd64
    samba+ccache-clang:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    freedesktop+pkgconfig:
      - version: ''
        architecture: []
    gnu+libtool:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
    gnu+m4:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
    llvm+llvm:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
    gnu+tar:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
data:
  get:
    uri: ''
    ref: ''
    out: ''
    externals: false
  type: bin
  configure: ''
  rules:
    type: meta
    location: ''
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
    other: {}
  embedded: true
