subpackage:
  - runtime*
name: qtgroup+qt6
version: 6.5.2
$version: 6.5.2
distribution: monolith/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Free and open-source cross-platform software for creating GUI.
  long: ''
dependency:
  install:
    adler+zlib:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    openssl+openssl:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    xorg+libx11:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+libxcb:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+xcb-util-image:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+xcb-util-keysyms:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+xcb-util-cursor:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+xcb-util-renderutil:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+xcb-util-wm:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    xkbcommon+libxkbcommon:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    freedesktop+libdbus:
      - version: ''
        architecture: []
        subpackage:
          - runtime
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    kitware+cmake:
      - version: ''
        architecture: []
    ninja+ninja:
      - version: ''
        architecture: []
  make:
    xcraft+base-make:
      - version: ''
        architecture: []
    wall+perl:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://code.qt.io/qt/qt5.git'
    mirrors: []
    ref: dev
    out: qt6
    externals: false
    prepare: |-
      !cd <THIS.DATA.RULES.LOCATION>
        && git checkout v<THIS.$VERSION>
        && perl init-repository --module-subset=qtbase,qtshadertools,qtdeclarative
    $ref: 9a94ba93db09e595baca5b7a063e897774b159ba
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && mkdir _build
      && cd _build
      && ../configure -prefix <PEON.PREFIXDIR>
                      -release
                      -shared
                      -ccache
                      -dbus-linked
                      -xcb
                      -qt-doubleconversion
                      -qt-freetype
                      -qt-harfbuzz
                      -qt-pcre
                      -no-glib
                      -no-icu
                      -no-inotify
                      -no-eventfd
                      -no-journald
                      -no-syslog
                      -no-slog2
                      -no-cups
                      -no-opengl
                      -no-linuxfb
  rules:
    type: script
    location: data/qt6
    args:
      postinst: ''
      prerm: ''
      makeall: '!cmake --build ./_build --parallel <PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: '!cmake --install ./_build'
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
