subpackage:
  - runtime*
name: perl+try-tiny
version: 0.30-2
$version: '0.30'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Minimal try/catch with proper preservation of $@
  long: ''
dependency:
  install:
    wall+perl:
      - version: ''
        architecture: []
        subpackage:
          - runtime
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    $hash: da5bd0d5c903519bbf10bb9ba0cb7bcac0563882bcfe4503aee3fb143eddef6b.tar.gz
  type: src
  configure: '!cd <THIS.DATA.RULES.LOCATION>/ && perl Makefile.PL PREFIX=<PEON.PREFIXDIR>'
  rules:
    type: make
    location: data/Try-Tiny-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
  deploy: rm('<PEON.PREFIXDIR>/lib/perl5/<PEON.ENV.XCRAFT_PERL_VERSION>/x86_64-linux/perllocal.pod')
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
