subpackage:
  - runtime*
name: torvalds+git
version: 2.10.1
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Git is a free and open source distributed version control system.
  long: >-
    Git is a free and open source distributed version control system designed to
    handle everything from small to very large projects with speed and
    efficiency.
dependency:
  install:
    bagder+curl:
      - version: ''
        architecture: []
    adler+zlib:
      - version: ''
        architecture: []
    clark+expat:
      - version: ''
        architecture: []
    openssl+openssl:
      - version: ''
        architecture: []
    gnu+libiconv:
      - version: ''
        architecture: []
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    toolchain+build-essential:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://github.com/git/git/archive/v<THIS.VERSION>.tar.gz'
    ref: ''
    out: ''
  type: src
  configure: ''
  rules:
    type: make
    location: data/git-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: >-
        -j<PEON.CPUS.COUNT> prefix=<PEON.PREFIXDIR> NO_GETTEXT=Yes NO_PERL=Yes
        NO_TCLTK=Yes <PEON.OS=darwin?:NO_ICONV=Yes> CC:=$(CC) CFLAGS:=$(CFLAGS)
        LDFLAGS:=$(LDFLAGS) NO_APPLE_COMMON_CRYPTO=1
      makeinstall: >-
        prefix=<PEON.PREFIXDIR> NO_GETTEXT=Yes NO_PERL=Yes NO_TCLTK=Yes
        <PEON.OS=darwin?:NO_ICONV=Yes> CC:=$(CC) CFLAGS:=$(CFLAGS)
        LDFLAGS:=$(LDFLAGS) NO_APPLE_COMMON_CRYPTO=1 install
  deploy: ''
  env:
    path: []
    other:
      GIT_EXEC_PATH: <OS.ROOTDIR>/usr/libexec/git-core
      GIT_TEMPLATE_DIR: <OS.ROOTDIR>/usr/share/git-core/templates
  embedded: true
  runtime:
    configure: ''
