subpackage:
  - runtime*
name: torvalds+git
version: 2.41.0
$version: 2.41.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Git is a free and open source distributed version control system.
  long: |-
    Git is a free and open source distributed version control system designed
    to handle everything from small to very large projects with speed and
    efficiency.
dependency:
  install:
    bagder+curl:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    adler+zlib:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    adler+zlib-dev:
      - version: ''
        architecture: []
    clark+expat:
      - version: ''
        architecture: []
        subpackage:
          - runtime
    openssl+openssl:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://github.com/git/git/archive/v<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 4f0b74bbde2800b00d3a50a7f389bcf1d59f1265b6986c00048d8ba4892ab01a.tar.gz
  type: src
  configure: ''
  rules:
    type: make
    location: data/git-<THIS.$VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT> prefix=<PEON.PREFIXDIR> NO_GETTEXT=Yes NO_PERL=Yes NO_TCLTK=Yes CC:=$(CC) CFLAGS:=$(CFLAGS) LDFLAGS:=$(LDFLAGS) NO_APPLE_COMMON_CRYPTO=1'
      maketest: ''
      makeinstall: 'prefix=<PEON.PREFIXDIR> NO_GETTEXT=Yes NO_PERL=Yes NO_TCLTK=Yes CC:=$(CC) CFLAGS:=$(CFLAGS) LDFLAGS:=$(LDFLAGS) NO_APPLE_COMMON_CRYPTO=1 install'
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other:
      GIT_EXEC_PATH: <OS.ROOTDIR>/usr/libexec/git-core
      GIT_TEMPLATE_DIR: <OS.ROOTDIR>/usr/share/git-core/templates
  embedded: true
  runtime:
    configure: ''
