name: schindelin+mingit
version: 2.39.2
$version: 2.39.2
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - mswindows-amd64
description:
  brief: Git is a free and open source distributed version control system.
  long: |-
    Git is a free and open source distributed version control system designed to
    handle everything from small to very large projects with speed and
    efficiency.
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://github.com/git-for-windows/git/releases/download/v<THIS.$VERSION>.windows.1/MinGit-<THIS.$VERSION>-busybox-64-bit.zip'
    mirrors: []
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: 'mv(''data'', ''root/opt/mingit'');'
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
    env: {}
  env:
    path:
      - opt/mingit/cmd
    other:
      GIT_CONFIG_KEY_0: core.longpaths
      GIT_CONFIG_VALUE_0: 'true'
      GIT_CONFIG_COUNT: '1'
  embedded: true
