name: schindelin+mingit
version: 2.10.0
$version: 2.10.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - mswindows-amd64
description:
  brief: Git is a free and open source distributed version control system.
  long: >-
    Git is a free and open source distributed version control system designed to
    handle everything from small to very large projects with speed and
    efficiency.
dependency:
  install:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
data:
  get:
    uri: >-
      https://github.com/git-for-windows/git/releases/download/v<THIS.$VERSION>.windows.1/MinGit-<THIS.$VERSION>-64-bit.zip
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: 'mv (''data'', ''root/opt/mingit'');'
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
  env:
    path:
      - opt/mingit/cmd
    other: {}
  embedded: true
