name: schindelin+mingit
version: 2.35.1.2
$version: 2.35.1.2
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - mswindows-amd64
description:
  brief: Git is a free and open source distributed version control system.
  long: |-
    Git is a free and open source distributed version control system designed to
    handle everything from small to very large projects with speed and
    efficiency.
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://github.com/git-for-windows/git/releases/download/v2.35.1.windows.2/MinGit-<THIS.$VERSION>-busybox-64-bit.zip'
    ref: ''
    out: ''
    externals: true
    $hash: aad8fe5975cb94bb550efbb0b4b696388de1d078296e1f31c268d144f6a6b0ea.zip
  type: bin
  configure: "mv('data', 'root/opt/mingit');"
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
  env:
    path:
      - opt/mingit/cmd
    other: {}
  embedded: true
