subpackage:
  - runtime*
name: gnu+libtool
version: 2.4.6
$version: 2.4.6
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: GNU libtool
  long: ''
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+m4:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture: []
    gnu+gcc:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
    llvm+llvm:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
data:
  get:
    uri: 'http://ftpmirror.gnu.org/libtool/libtool-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    $hash: e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
    <PEON.OS=darwin?
                     --program-prefix=g
    :>
  rules:
    type: make
    location: data/libtool-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
  deploy: |-
    rm('<PEON.PREFIXDIR>/share/info/dir');
    <PEON.OS=darwin?
      cp('{PEON.PREFIXDIR}/bin/glibtoolize', '{PEON.PREFIXDIR}/bin/libtoolize');
    :>
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
