subpackage:
  - runtime*
name: freedesktop+pkgconfig
version: 0.29.2-5
$version: 0.29.2
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: helper tool used when compiling applications and libraries
  long: |-
    It helps you insert the correct compiler options on the command line so an
    application can use gcc -o test test.cpkg-config --libs --cflags glib-2.0
    for instance, rather than hard-coding values on where to find glib (or other
    libraries). It is language-agnostic, so it can be used for defining the
    location of documentation tools, for instance.
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
    gnu+gcc:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
    llvm+llvm:
      - version: ''
        architecture:
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
data:
  get:
    uri: 'https://pkg-config.freedesktop.org/releases/pkg-config-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    $hash: 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591.tar.gz
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --with-internal-glib
                     --disable-nls
                     --disable-host-tool
                     --disable-maintainer-mode
                     --disable-indirect-deps
  rules:
    type: make
    location: data/pkg-config-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
    env:
      darwin/LDFLAGS: '-framework CoreFoundation -framework Carbon'
      darwin/CFLAGS: '<PEON.ENV.CFLAGS> -Wno-int-conversion'
      win/MSYSTEM: MINGW64
  deploy: ''
  env:
    path: []
    other:
      PKG_CONFIG_PATH: '<OS.PROD.ROOTDIR>/usr/lib/pkgconfig<OS.NAME=win32?;::><OS.PROD.ROOTDIR>/usr/share/pkgconfig'
  embedded: true
  runtime:
    configure: ''
