subpackage:
  - runtime*
name: freedesktop+pkgconfig
version: 0.29.1
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: helper tool used when compiling applications and libraries
  long: >-
    It helps you insert the correct compiler options on the command line so an
    application can use gcc -o test test.cpkg-config --libs --cflags glib-2.0
    for instance, rather than hard-coding values on where to find glib (or other
    libraries). It is language-agnostic, so it can be used for defining the
    location of documentation tools, for instance.
dependency:
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture: []
    gnu+gcc:
      - version: ''
        architecture: []
data:
  get:
    uri: >-
      https://pkg-config.freedesktop.org/releases/pkg-config-<THIS.VERSION>.tar.gz
    ref: ''
    out: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && <PEON.OS=darwin?LDFLAGS="-framework
    CoreFoundation -framework Carbon":> ./configure --prefix=<PEON.PREFIXDIR>
    --with-internal-glib
  rules:
    type: make
    location: data/pkg-config-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      makeinstall: install
  deploy: ''
  env:
    path: []
    ldpath: []
    other:
      PKG_CONFIG_PATH: <OS.ROOTDIR>/usr/lib/pkgconfig
  embedded: true
  runtime:
    configure: ''
