name: toolchain+xcraft-atom
version: 0.1.0
maintainer:
  name: Samuel Loup
  email: "loup@epsitec.ch"
architecture:
  - all
description:
  brief: Xcraft atom-shell runtime
  long: "Needed for graphical interfaces"
dependency:
  runtime:
    bootstrap+xcraft-peon:
      - ""
data:
  uri: "self:///root"
  type: bin
  configure: "cp ('<PEON.XCRAFTHOME>/xdk/xcraft-atom', '<PEON.WPKGSTAG>/usr/share/toolchain/xcraft-atom');"
  rules:
    type: copy
    location: ""
    args:
      postinst: ""
      prerm: ""
  embedded: true
distribution: toolchain/
