name: toolchain+xcraft-atom
version: 0.1.0
distribution: toolchain/
maintainer:
  name: Samuel Loup
  email: loup@epsitec.ch
architecture:
  - all
description:
  brief: Xcraft atom-shell runtime
  long: Needed for graphical interfaces
dependency:
  install:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'self:///root'
    ref: ''
    out: ''
  type: bin
  configure: "cp ('<PEON.XCRAFT.HOME>/xdk/xcraft-atom', '<PEON.WPKG.STAG>/usr/share/toolchain/xcraft-atom');"
  rules:
    type: copy
    location: ''
    args:
      postinst: ''
      prerm: ''
  path: []
  embedded: true
