name: xcraft+peon
version: 1.6.1
$version: 1.6.1
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - all
description:
  brief: A core dependency for many packages.
  long: ''
dependency:
  install:
    xcraft+devrootfs:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'self:///root'
    mirrors: []
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: |-
    cp('.', '<PEON.WPKG.STAG>');
    cd('<PEON.WPKG.STAG>/usr/share/xcraft/peon');
    yield exec('npm', 'install', '--omit=dev');
  rules:
    type: configure
    location: ''
    args:
      postinst: ''
      prerm: ''
    env: {}
  env:
    path: []
    other:
      C_INCLUDE_PATH: <OS.PROD.ROOTDIR>/usr/include
      CPLUS_INCLUDE_PATH: <OS.PROD.ROOTDIR>/usr/include
      LIBRARY_PATH: <OS.PROD.ROOTDIR>/usr/lib
      XCRAFT_DEVROOT: <OS.ROOTDIR>
      XCRAFT_TARGETROOT: <OS.PROD.ROOTDIR>
  embedded: true
