name: xcraft+peon
version: 0.2.0-3
$version: 0.2.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - all
description:
  brief: A core dependency for many packages.
  long: ''
dependency:
  install:
    xcraft+devrootfs:
      - version: ''
        architecture: []
data:
  get:
    uri: 'self:///root'
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: ''
  rules:
    type: copy
    location: ''
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
    other:
      C_INCLUDE_PATH: <OS.PROD.ROOTDIR>/usr/include
      CPLUS_INCLUDE_PATH: <OS.PROD.ROOTDIR>/usr/include
      LIBRARY_PATH: <OS.PROD.ROOTDIR>/usr/lib
      XCRAFT_DEVROOT: <OS.ROOTDIR>
      XCRAFT_TARGETROOT: <OS.PROD.ROOTDIR>
  embedded: true
