name: schindelin+msysgit
version: 1.9.5-preview20141217
$version: 1.9.5-preview20141217
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: Git is a free and open source distributed version control system.
  long: >-
    Git is a free and open source distributed version control system designed to
    handle everything from small to very large projects with speed and
    efficiency.
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'chest:portablegit-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
  type: bin
  configure: 'mv (''data'', ''root/opt/msysgit'');'
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
  env:
    path:
      - opt/msysgit/cmd
    other: {}
  embedded: true
