data:
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION> &&
    <PEON.OS=darwin?
      SDKROOT="$MACOSSDK_1013"
      MACOSX_DEPLOYMENT_TARGET=10.13
    :> ./configure --prefix=<PEON.PREFIXDIR>
                   --enable-static
                   --enable-shared
  rules:
    args:
      makeall: |-
        !<PEON.OS=darwin?
          SDKROOT="$MACOSSDK_1013"
          MACOSX_DEPLOYMENT_TARGET=10.13
        :> make -j<PEON.CPUS.COUNT>
