subpackage:
  - runtime*
name: gnu+bison
version: 3.0.4
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Bison.
  long: ''
dependency:
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    gnu+help2man:
      - version: ''
        architecture: []
    wall+perl:
      - version: ''
        architecture: []
    gnu+m4:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://mirror.switch.ch/ftp/mirror/gnu/bison/bison-<THIS.VERSION>.tar.gz'
    ref: ''
    out: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && ./configure --prefix=<PEON.PREFIXDIR>
    --disable-rpath --disable-nls
  rules:
    type: make
    location: data/bison-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      makeinstall: install
  deploy: ''
  env:
    path: []
    ldpath: []
    other:
      BISON_PKGDATADIR: <OS.ROOTDIR>/usr/share/bison
  embedded: true
  runtime:
    configure: ''
