name: toolchain+xcraft-gui
version: 0.1.0
maintainer:
  name: Samuel Loup
  email: "loup@epsitec.ch"
architecture:
  - all
description:
  brief: Xcraft GUI
  long: "Manage and edit Xcraft packages and settings"
dependency:
  toolchain+xcraft-goblin:
    - ""
  bootstrap+xcraft-peon:
    - ""
data:
  uri: "self:///root"
  type: bin
  rules:
    type: copy
    location: ""
    args:
      postinst: ""
      prerm: ""
  embedded: true
distribution: toolchain/
