name: toolchain+xcraft-gui
version: 0.1.0
maintainer:
  name: Samuel Loup
  email: "loup@epsitec.ch"
architecture:
  - all
description:
  brief: Xcraft GUI
  long: Manage and edit Xcraft packages and settings
dependency:
  install:
    toolchain+xcraft-goblin:
      - ""
    bootstrap+xcraft-peon:
      - ""
data:
  get:
    uri: "self:///root"
  type: bin
  configure: "cp ('<PEON.XCRAFT.HOME>/xdk/xcraft-gui', '<PEON.WPKG.STAG>/usr/share/toolchain/xcraft-gui');"
  rules:
    type: copy
    location: ""
    args:
      postinst: ""
      prerm: ""
  path: []
  embedded: true
distribution: toolchain/
