subpackage:
  - runtime*
name: lzmautils+xz
version: 5.2.5
$version: 5.2.5
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Data compression software with a high compression ratio
  long: ''
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://fossies.org/linux/misc/xz-<THIS.$VERSION>.tar.bz2'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --enable-static
                     --disable-shared
                     --disable-nls
                     --enable-xz
                     --disable-xzdec
                     --disable-lzmadec
                     --disable-lzmainfo
                     --disable-lzma-links
                     --disable-scripts
                     --disable-doc
    <PEON.OS=win?    --disable-threads :>
  rules:
    type: script
    location: data/xz-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!<PEON.OS=win? mingw32-make : make > -j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: '!<PEON.OS=win? mingw32-make : make > install'
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
