data:
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --host=aarch64-linux
                     --build=$MACHTYPE
                     --disable-shared
                     --enable-static
                     --disable-ldap
                     --disable-ldaps
                     --with-openssl
  rules:
    env:
      CC: aarch64-linux-gcc
      CXX: aarch64-linux-g++
