data:
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --disable-shared
                     --enable-static
                     --disable-ldap
                     --disable-ldaps
  rules:
    env:
      darwin/SDKROOT: <PEON.ENV.MACOSSDK_1013>
      darwin/MACOSX_DEPLOYMENT_TARGET: '10.10'