data:
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --enable-shared
                     --disable-static
                     --disable-ldap
                     --disable-ldaps
    <PEON.OS=darwin?
                     --with-secure-transport
    :
                     --with-openssl
    >
