data:
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION> &&
    ./configure --prefix=<PEON.PREFIXDIR>
                --enable-shared
                --disable-static
                --disable-ldap
                --disable-ldaps
                --with-openssl
