name: toolchain+xcraft-goblin
version: 0.1.0
maintainer:
  name: Samuel Loup
  email: "loup@epsitec.ch"
architecture:
  - all
description:
  brief: Xcraft Desktop Manager
  long: "Manage your workspace, and run funny crafted gadget'apps!"
dependency:
  runtime:
    toolchain+xcraft-atom:
      - ""
    bootstrap+xcraft-peon:
      - ""
data:
  uri: "self:///root"
  type: bin
  configure: "cp ('<PEON.XCRAFTHOME>/xdk/xcraft-goblin', '<PEON.WPKGSTAG>/usr/share/toolchain/xcraft-goblin');"
  rules:
    type: copy
    location: ""
    args:
      postinst: ""
      prerm: ""
  path: []
  embedded: true
distribution: toolchain/
