name: toolchain+xcraft-goblin
version: 0.1.0
distribution: toolchain/
maintainer:
  name: Samuel Loup
  email: loup@epsitec.ch
architecture:
  - all
description:
  brief: Xcraft Desktop Manager
  long: "Manage your workspace, and run funny crafted gadget'apps!"
dependency:
  install:
    toolchain+xcraft-atom:
      - version: ''
        architecture: []
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
data:
  get:
    uri: 'self:///root'
    ref: ''
    out: ''
  type: bin
  configure: "cp ('<PEON.XCRAFT.HOME>/xdk/xcraft-goblin', '<PEON.WPKG.STAG>/usr/share/toolchain/xcraft-goblin');"
  rules:
    type: copy
    location: ''
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
  embedded: true
