name: microsoft+dotnet-sdk-win
version: 23.0.0
$version: 23.0.0
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - mswindows-i386
  - mswindows-amd64
description:
  brief: .NET Core SDK 6.0, 8.0 and 9.0
  long: ''
dependency:
  install:
    xcraft+peon:
      - version: ''
        architecture: []
  make:
    microsoft+dotnet-sdk-60-win:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
    microsoft+dotnet-sdk-80-win:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
    microsoft+dotnet-sdk-90-win:
      - version: ''
        architecture:
          - mswindows-i386
          - mswindows-amd64
bump: []
data:
  get:
    uri: ''
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: false
  type: bin
  configure: |-
    cp('<PEON.ROOTDIR>/usr/share/microsoft/dotnet-sdk-60-win/cache/data', 'root/opt/dotnet-sdk');
    cp('<PEON.ROOTDIR>/usr/share/microsoft/dotnet-sdk-80-win/cache/data', 'root/opt/dotnet-sdk');
    cp('<PEON.ROOTDIR>/usr/share/microsoft/dotnet-sdk-90-win/cache/data', 'root/opt/dotnet-sdk');
  rules:
    type: move
    location: root
    args:
      postinst: ''
      prerm: ''
    env: {}
  env:
    path:
      - opt/dotnet-sdk
    other:
      DOTNET_ROOT: <OS.ROOTDIR>/opt/dotnet-sdk
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      MSBUILDDISABLENODEREUSE: '1'
  embedded: true
