subpackage:
  - runtime*
name: linux+kernel
version: 5.8.13-1
$version: 5.8.13
distribution: carnotzet/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: The Linux Kernel
  long: ''
dependency:
  install:
    vlasenko+busybox:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+bc:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-<THIS.$VERSION>.tar.xz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && make ARCH=arm64 CROSS_COMPILE=aarch64-linux- defconfig
      && sed -i 's,^CONFIG_INITRAMFS_SOURCE="",CONFIG_INITRAMFS_SOURCE="<PEON.PROD.ROOTDIR>/var/aarch64-linux/rootfs"\nCONFIG_INITRAMFS_COMPRESSION_GZIP=y,' .config
      && make ARCH=arm64 CROSS_COMPILE=aarch64-linux- olddefconfig
      && mkdir -p "<PEON.INSTALLDIR>/var/aarch64-linux/kernel"
  rules:
    type: script
    location: data/linux-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !export KBUILD_BUILD_TIMESTAMP=''
          && make ARCH=arm64 CROSS_COMPILE=aarch64-linux- -j<PEON.CPUS.COUNT>
      maketest: ''
      makeinstall: |-
        !make ARCH=arm64
              CROSS_COMPILE=aarch64-linux-
              INSTALL_MOD_PATH="<PEON.INSTALLDIR>/var/aarch64-linux/rootfs"
            modules_install
          && cp -a arch/arm64/boot/Image "<PEON.INSTALLDIR>/var/aarch64-linux/kernel"
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
