dependency:
  build:
    x-arm-linux+gnueabihf-gcc-glibc-cross:
      - version: ''
        architecture: []
data:
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && make ARCH=arm CROSS_COMPILE=arm-xcraft-linux-gnueabihf- defconfig
      && sed -i 's,^CONFIG_INITRAMFS_SOURCE="",CONFIG_INITRAMFS_SOURCE="<PEON.PROD.ROOTDIR>/var/arm-linux/rootfs <PEON.PROD.ROOTDIR>/var/arm-linux/root-files"\nCONFIG_INITRAMFS_COMPRESSION_GZIP=y,' .config
      && make ARCH=arm CROSS_COMPILE=arm-xcraft-linux-gnueabihf- olddefconfig
      && mkdir -p "<PEON.INSTALLDIR>/var/arm-linux/kernel"
  rules:
    args:
      makeall: |-
        !make ARCH=arm
              CROSS_COMPILE=arm-xcraft-linux-gnueabihf-
              -j<PEON.CPUS.COUNT>
      makeinstall: |-
        !: /// disable module installation /// make ARCH=arm
              CROSS_COMPILE=arm-xcraft-linux-gnueabihf-
              INSTALL_MOD_PATH="<PEON.INSTALLDIR>/var/arm-linux/rootfs"
            modules_install
          && cp -a arch/arm/boot/Image "<PEON.INSTALLDIR>/var/arm-linux/kernel"
  get:
    $hash: 9597c4fee2f1ce452acfec516f4325ad342155872052fd5f0d9ce2ddcc26ebe5.tar.xz
