subpackage:
  - runtime*
name: perl+module-build
version: '0.4229-1'
$version: '0.4229'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Build and install Perl modules
  long: ''
dependency:
  install:
    wall+perl:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
data:
  get:
    uri: >-
      https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-<THIS.$VERSION>.tar.gz
    ref: ''
    out: ''
    externals: true
  type: src
  configure: '!cd <THIS.DATA.RULES.LOCATION>/ && perl Build.PL'
  rules:
    type: script
    location: data/Module-Build-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!./Build'
      maketest: ''
      makeinstall: '!./Build install --prefix=<PEON.PREFIXDIR>'
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
