subpackage:
  - runtime*
name: gnu+libiconv
version: '1.14'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: An API used to convert between different character encodings.
  long: ''
dependency:
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    toolchain+build-essential:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftp.gnu.org/pub/gnu/libiconv/libiconv-<THIS.VERSION>.tar.gz'
    ref: ''
    out: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && ./configure --disable-nls
    --prefix=<PEON.PREFIXDIR>
  rules:
    type: make
    location: data/libiconv-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      makeinstall: install
  deploy: >-
    <PEON.OS=darwin?!install_name_tool -id @rpath/libiconv.2.dylib
    "<PEON.PREFIXDIR>/lib/libiconv.2.dylib" && install_name_tool -id
    @rpath/libcharset.1.dylib "<PEON.PREFIXDIR>/lib/libcharset.1.dylib" &&
    install_name_tool -change "<PEON.PREFIXDIR>/lib/libiconv.2.dylib"
    @rpath/libiconv.2.dylib "<PEON.PREFIXDIR>/bin/iconv":>
  env:
    path: []
    ldpath: []
    other: {}
  embedded: true
  runtime:
    configure: ''
