subpackage:
  - runtime*
name: gnu+libiconv
version: '1.14'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: An API used to convert between different character encodings.
  long: ''
dependency:
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    toolchain+build-essential:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftp.gnu.org/pub/gnu/libiconv/libiconv-<THIS.VERSION>.tar.gz'
    ref: ''
    out: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && ./configure --disable-nls
    --prefix=<PEON.PREFIXDIR>
  rules:
    type: make
    location: data/libiconv-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      makeinstall: install
  deploy: rpathFixup ('<PEON.PREFIXDIR>');
  env:
    path: []
    ldpath: []
    other: {}
  embedded: true
  runtime:
    configure: ''
