subpackage:
  - runtime*
name: samba+ccache
version: 3.3.2
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: A fast C/C++ compiler cache.
  long: >-
    ccache is a compiler cache. It speeds up recompilation by caching previous
    compilations and detecting when the same compilation is being done again.
    Supported languages are C, C++, Objective-C and Objective-C++.
dependency:
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://www.samba.org/ftp/ccache/ccache-<THIS.VERSION>.tar.bz2'
    ref: ''
    out: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && ./configure
    --prefix=<PEON.PREFIXDIR>/local
  rules:
    type: make
    location: data/ccache-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      makeinstall: install
  deploy: >-
    !ln -s ccache <PEON.INSTALLDIR>/usr/local/bin/gcc; ln -s ccache
    <PEON.INSTALLDIR>/usr/local/bin/g++; ln -s ccache
    <PEON.INSTALLDIR>/usr/local/bin/cc; ln -s ccache
    <PEON.INSTALLDIR>/usr/local/bin/c++
  env:
    path: []
    ldpath: []
    other:
      CC: <OS.ROOTDIR>/usr/local/bin/gcc
      CXX: <OS.ROOTDIR>/usr/local/bin/g++
      CCACHE_DIR: <OS.ROOTDIR>/var/ccache
  embedded: true
  runtime:
    configure: ''
