subpackage:
  - runtime*
name: samba+ccache
version: 3.7.12
$version: 3.7.12
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: A fast C/C++ compiler cache.
  long: |-
    ccache is a compiler cache. It speeds up recompilation by caching previous
    compilations and detecting when the same compilation is being done again.
    Supported languages are C, C++, Objective-C and Objective-C++.
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
data:
  get:
    uri: 'https://github.com/ccache/ccache/releases/download/v<THIS.$VERSION>/ccache-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: d2abe88d4c283ce960e233583061127b156ffb027c6da3cf10770fc0c7244194.tar.gz
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
  rules:
    type: make
    location: data/ccache-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install
    test: none
    env:
      win/LDFLAGS: <PEON.ENV.LDFLAGS> -lws2_32
      win/MSYSTEM: MINGW64
  deploy: ''
  env:
    path: []
    other:
      CCACHE_DIR: <OS.ROOTDIR>/var/ccache
      CCACHE_NOHASHDIR: 'true'
  embedded: true
  runtime:
    configure: ''
