subpackage:
  - runtime*
name: openssl+openssl
version: 1.1.0b
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: OpenSSL
  long: ''
dependency:
  install:
    adler+zlib:
      - version: ''
        architecture: []
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    toolchain+build-essential:
      - version: ''
        architecture: []
    wall+perl:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://www.openssl.org/source/openssl-<THIS.VERSION>.tar.gz'
    ref: ''
    out: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && CC="$CC $CFLAGS"
    ./<PEON.OS=darwin?Configure darwin64-x86_64-cc:config> shared
    --prefix=<PEON.PREFIXDIR>
  rules:
    type: make
    location: data/openssl-<THIS.VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: CFLAGS= LDFLAGS= -j<PEON.CPUS.COUNT>
      makeinstall: CFLAGS= LDFLAGS= install_sw
  deploy: rpathFixup ('<PEON.PREFIXDIR>');
  env:
    path: []
    ldpath: []
    other: {}
  embedded: true
  runtime:
    configure: ''
