subpackage:
  - runtime*
name: openssl+openssl
version: 1.1.1a-1
$version: 1.1.1a
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: OpenSSL
  long: ''
dependency:
  install:
    adler+zlib:
      - version: ''
        architecture: []
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    wall+perl:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://www.openssl.org/source/openssl-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && CC="$CC $CFLAGS"
    ./<PEON.OS=darwin?Configure darwin64-x86_64-cc:config> shared
    --prefix=<PEON.PREFIXDIR>
  rules:
    type: make
    location: data/openssl-<THIS.$VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: CFLAGS= LDFLAGS= -j<PEON.CPUS.COUNT>
      maketest: ''
      makeinstall: CFLAGS= LDFLAGS= install_sw
    test: none
  deploy: ''
  env:
    path: []
    other:
      SSL_CERT_DIR: /etc/ssl/certs
  embedded: true
  runtime:
    configure: ''
