subpackage:
  - runtime*
name: openssl+openssl
version: 1.1.1a-7
$version: 1.1.1a
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: OpenSSL
  long: ''
dependency:
  install:
    adler+zlib-dev:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
    wall+perl:
      - version: ''
        architecture:
          - linux-i386
          - linux-amd64
          - linux-aarch64
          - darwin-i386
          - darwin-amd64
          - darwin-aarch64
          - solaris-i386
          - solaris-amd64
          - freebsd-i386
          - freebsd-amd64
data:
  get:
    uri: 'https://www.openssl.org/source/openssl-<THIS.$VERSION>.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION> &&
    CC="${CC:-cc} $CFLAGS"
    <PEON.OS=darwin?
      ./Configure darwin64-{PEON.OS.ARCH2}-cc
    :>
    <PEON.OS=win?
      ./Configure mingw64
    :>
    <PEON.OS=linux?
      ./config
    :> shared --prefix=<PEON.PREFIXDIR>
  rules:
    type: script
    location: data/openssl-<THIS.$VERSION>/
    args:
      postinst: ''
      prerm: ''
      makeall: '!make CFLAGS= LDFLAGS= -j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: '!make CFLAGS= LDFLAGS= install_sw'
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other:
      SSL_CERT_DIR: /etc/ssl/certs
  embedded: true
  runtime:
    configure: ''
