data:
  configure: >-
    !cd <THIS.DATA.RULES.LOCATION> && CC="$CC $CFLAGS"
    ./<PEON.OS=darwin?Configure darwin64-x86_64-cc:config>
    <PEON.OS=darwin?no-shared:shared> --prefix=<PEON.PREFIXDIR>
