name: toolchain+build-essential
version: 0.0.1
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - linux-i386
  - linux-amd64
  - darwin-i386
  - darwin-amd64
  - solaris-i386
  - solaris-amd64
  - freebsd-i386
  - freebsd-amd64
description:
  brief: Essential tools for building.
  long: ''
dependency:
  install:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    gnu+gcc:
      - version: ''
        architecture: []
    gnu+make:
      - version: ''
        architecture: []
    samba+ccache:
      - version: ''
        architecture: []
    gnu+libiconv:
      - version: ''
        architecture: []
    freedesktop+pkgconfig:
      - version: ''
        architecture: []
    gnu+libtool:
      - version: ''
        architecture: []
    gnu+m4:
      - version: ''
        architecture: []
data:
  get:
    uri: ''
    ref: ''
    out: ''
  type: bin
  configure: ''
  rules:
    type: meta
    location: ''
    args:
      postinst: ''
      prerm: ''
  env:
    path: []
    other: {}
  embedded: true
