subpackage:
  - runtime*
name: debian+debhelper
version: '12.3'
distribution: toolchain/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Debien helpers
  long: ''
dependency:
  install:
    wall+perl:
      - version: ''
        architecture: []
  build:
    toolchain+xcraft-peon:
      - version: ''
        architecture: []
    toolchain+build-essential:
      - version: ''
        architecture: []
    mquinson+po4a:
      - version: ''
        architecture: []
data:
  get:
    uri: >-
      http://ftp.debian.org/debian/pool/main/d/debhelper/debhelper_<THIS.VERSION>.tar.xz
    ref: ''
    out: ''
    externals: true
  type: src
  configure: ''
  rules:
    type: make
    location: data/debhelper/
    args:
      postinst: ''
      prerm: ''
      makeall: >-
        build -j<PEON.CPUS.COUNT> PREFIX=<PEON.PREFIXDIR>
        PERLLIBDIR=<PEON.PREFIXDIR>/lib/perl5/site_perl/Debian/Debhelper
      maketest: ''
      makeinstall: >-
        install PREFIX=<PEON.PREFIXDIR>
        PERLLIBDIR=<PEON.PREFIXDIR>/lib/perl5/site_perl/Debian/Debhelper
    test: none
  deploy: >-
    batch.sed('<PEON.PREFIXDIR>/bin/', /^#!\/usr\/bin\/perl\n/, '#!/usr/bin/env
    perl'); batch.sed('<PEON.PREFIXDIR>/bin/', /^#!\/usr\/bin\/perl -w\n/,
    '#!/usr/bin/env -S perl -w');
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
